name: Deploy v2 to GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy v2 folder
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: v2               
          clean: true         