name: Deploy v2 to GitHub Pages
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy v2 folder
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: v       
          clean: true         